ai-concept-demo/concept-demo.py

#12 파일 읽을때 예외처리 되지 못하는 문제를 파일이 없으면 예외처리 되도록 바꿔봤습니다.

#12 exception handling add

---

Dockerfile
requirements.txt

컴퓨터에 도커를 실행할 수 있는 환경이 갖추어져 있다는 가정에서
coursegraph-py-main 디렉토리 내부로 들어와
docker build -t test . 
[docker images] build 가 제대로 되어있는지 확인 <-- 생략가능
docker container run test
명령을 순차적으로 사용함으로써 컨테이너 내부에서 개발환경이 세팅된 후, concept-demo.py 코드가 실행됨을 확인

도커 컨테이너를 활용한 개발 환경 단순화

---

ai-concept-demo/concept-demo.py
ai-concept-demo/show_yaml.py
requirements.txt

#30 input.yaml에 있는 과목 내용들을 표로 만들어서 출력하는 파이썬 파일입니다. 파일을 실행하면 과목 표가 나옵니다.

input.yaml에 있는 과목 정보들을 보기 좋게 표로 출력하는 파이썬 파일입니다.

---

ai-concept-demo/concept-demo.py

plt.figure 를 추가해 figure 사이즈를 조정하여 출력되어지는 배경에 더 많은 정보가 들어갈 수 있도록 조정했습니다.

Matplotlib의 기본 사이즈 figure를 지정했습니다.

---

ai-concept-demo/concept-demo.py

중복 코드 최소화 pr

---

coursegraph/__main__.py

Update __main__.py 가볍게 수정

---

coursegraph/fontutil.py

fontutil에서 선언된 변수 이름에 오타가 있어 수정하였습니다.

fontutil 오타가 있어 수정하였습니다.

---

coursegraph/__main__.py
coursegraph/fontutil.py

읽어들일 yaml파일을 GUI 형식으로 data폴더 내 yaml을 선택하고, 선택한 파일의 경로를 리턴하는 함수를 추가하였습니다. 추후에 전공 이수 체계도를 그리는 코드가 추가되면 활용하면 좋을 듯 싶어서 함수를 추가해보았습니다.

읽어들일 파일을 선택하여 경로를 제공하는 함수를 추가하였습니다.

---

coursegraph/show_yaml.py

show_yaml.py 의 22번째 줄에서 나는 인덱스 에러를 수정하였습니다.

IndexError: list index out of range 수정

---

coursegraph/__main__.py
coursegraph/show_yaml.py

출력된 이미지가 저장되는 기능이 없어서 -s 옵션으로 표를 출력할때 -img 옵션을 같이 사용하면 img를 저장할 수 있도록 수정해보았습니다.

표를 출력하고 이미지를 저장할 수 있도록 하였습니다. 

---

coursegraph/__main__.py
coursegraph/show_graph.py
coursegraph/show_table.py

기존에 input을 입력받아도 다시 yaml 파일의 이름을 입력받는 것을 받지않고 input 값을 사용하도록 하였고, output을 입력 시에  입력받은 이름의 이미지 파일을 생성하도록 하였습니다.
추가로 show_graph 에서 sys.stderr를 사용하는데에 반해 sys 모듈이 import 되어 있지않아 추가하였습니다.

input과 output을 연동하여 show_table을 사용하도록 수정하였습니다.

---

coursegraph/show_graph.py

input.yaml로 테스트해본 결과
수정 전
수정 후
다른 yaml에서도 동일하게 적용되는 것을 테스트를 통해 확인했습니다.
* resolved #94

1학기 2학기 노드 위치 수정

---

coursegraph/Maingui.ui
coursegraph/gui.py
coursegraph/show_graph.py

#249 Issues입니다.
#247 의 문제 해결코드에서부터 PR하였습니다.
#246 에서 PushButton잘림 문제도 해결할 수 있을걸로 생각됩니다.
기존 사이즈를 줄였을 때
수정 후 사이즈를 줄였을 때
기존 사이즈를 키웠을 때
수정 후 사이즈를 키웠을 때
Layout을 설정하여 주고, Margin을 0으로 설정하여 항상 실행되는 GUI에서 꽉차서 보일 수 있게 해두었습니다.

동적 창 크기 조절

---

coursegraph/show_table.py

코드를 여러 번을 실행하면서 폰트를 찾는 방식을 한 번의 시스템 폰트 조회를 통해 반환하는 방식의 코드를 수정했습니다.

코드의 간결화를 통한 가독성 확보

---

coursegraph/__main__.py

#257 
사용되지 않는 옵션 verbose를 삭제했습니다.

Delete Option Verbose

---

README.md

md파일에 각 개발 환경에서 qt desiner 를 사용할 수 있는 방법을 명시했습니다.

md 파일에 qt desiner 사용법 추가

---

coursegraph/show_graph.py

현재 pydoc 를 사용하기 위한 코드들의 주석들이 부족한 것 같아서 첫번째로 show_graph.py 에 간단한 주석을 달아보았습니다.
그리고 가독성을 위해 PEP8 파이썬 코드 작성 표준에 맞춰 띄어쓰기등을 수정하였습니다.
일단은 어떤 방식으로 주석을 달았는지 보여주기 위해 하나의 파일만을 push 하였습니다. 다음 pr 때는 한꺼번에 주석을 처리한 후에 pr 할 예정입니다.

docstring을 위해 show_graph.py 의 주석을 추가했습니다.

---

README.md

#284에서 "코드스페이스에서 폰트를 다운로드 하면 코드스페이스를 재부팅(?) 해야 하는걸로 알고 있기에 하는 방법등을 적으면 좋을 것 같습니다."
라는 이슈를 바탕으로, 명령어 실행 후 코드스페이스를 재부팅 하는 방법까지 README.md에 추가하였습니다

Update README.md 한글 폰트 설치 방법 업데이트

---

coursegraph/show_graph.py

#300 
새로 코드가 병합되면서 이전에 수정했던 부분이 사라진 것 같아 다시 수정하였습니다.

94db0e8 버전에서 그래프 출력 시 한글 출력 오류 문구 발생 해결

---

coursegraph/__main__.py
coursegraph/show_graph.py
coursegraph/show_table.py

- __main__.py 에서 -s 옵션을 추가하였습니다.
- 이전에는 사이즈를 바꾸고 싶었다면 코드 안에서 figsize를 찾아야 했기에 불편함이 있었던 반면 -s 사용자 옵션을 추가 하였기에 코드스페이스에서 쉽게 바꿀 수 있고 -s 사용자 옵션을 사용하지 않더라도 불편함이 없게 dafault 값도 설정을 하였습니다.
- 만약 default 값을 바꾸고 싶으면 main 에서 args.size 만 찾으면 되기에 전에 비해 코드를 찾는 것도 수월해졌습니다.
- -s 옵션을 사용하고 싶다면 python coursegraph -f graph -i data/input.yaml -o graph.png -s 10,10 과 같이 사용하면 됩니다.
- -s 옵션을 사용하지 않더라도 이전과 같이 python coursegraph -f graph -i data/input.yaml -o graph.png 과 같이 사용하면 default 값으로 사이즈가 지정이 됩니다.

main CLI에서 사용자 지정 -s 옵션 추가

---

coursegraph/schema_checker.py

그리고 코드 가독성을 위해 PEP8 에 맞춰 줄맞춤이나 띄어쓰기등을 수정하였습니다.
pydoc 로 확인할 수 있게 하였습니다. 
하지만 이 파일 자체가 실행을 하기 때문에 if __name__ : "__main__" : 같은 조건문 처리나
실행문들을 함수로 묶는 것이 좋을거 같습니다.

schema_checker.py 의 주석을 추가했습니다. 

---

README.md

새로 추가된 CLI 명령어 -s 옵션에 대한 기능을 README에 사용법과 기능설명을 추가하였습니다.

#315 이슈 해결 (README CLI 사용법 -s 옵션 기능 설명 추가)

---

coursegraph/show_table.py

#272 이슈의 따라
각 함수의 문서화 중 show_table.py 에 대한 문서화를 진행했습니다.
기존 docstring 과 유사한 형식으로 작성했습니다. #272

#272 각 함수의 문서화 show_table docstring 작성

---

coursegraph/show_graph.py

노드좌표배치 수식을 좀더 손봤습니다. 수식을 통해서 노드들의 간격을 계산하는 것이 아닌,  내부 그래프 기준점으로부터 시작하여 일정한 간격으로 노드들을 배치하는 구조로 변경하였습니다. 이런 방식으로 첫 노드가 음수값이 되는것을 방지합니다

#351 이슈 해결

---

coursegraph/schema_checker.py

1. 재사용성 향상 - validate_yaml 함수와 validate_string_or_sequence 함수를 다른 스크립트나 모듈에서 쉽게 재사용할 수 있습니다. 중복 코드를 줄이고 코드이 유지보수성을 높였습니다.
2. 코드의 명확한 구조화 - if __name__ == '__main__': 조건문을 사용함으로써 코드가 의도치 않게 실행되는 것을 방지할 수 있습니다. 또한, 코드의 가독성이 향상되어 이해와 수정을 도왔습니다.

#310 schema_checker.py 를 실행할때 실행할 명령문의 함수 개선

---

coursegraph/__main__.py
coursegraph/show_table.py

output 파일 명 끝에 .pdf면 pdf로 출력되도록 추가했습니다.
Excel로 출력하는 기능은 어려워서 아직 못했습니다.
실행 명령어: python coursegraph -i data/ce.yaml -o out2.pdf

 pdf형식으로 출력 가능하도록 추가

---

coursegraph/__main__.py

CLI 입력 인자 검증 강화 수정본입니다.

---

coursegraph/gui.py

Openfuction 함수내의 내에서 위에 기능을 추가하기 위해 다음과 같은 코드를 추가
self.adjustSize() # 윈도우 크기 조정
self.statusBar().showMessage(f"Opened image: {filename}", 5000) # 상태바에 메시지 표시
self.addRecentFile(filename) # 최근 파일 목록에 추가

최근에 연 파일 목록을 관리하여 빠르게 접근할 수 있게 하는 기능 추가

---

README.md
coursegraph/show_graph.py

↑ https://github.com/oss2024hnu/coursegraph-py/commit/f53066931eacfaecc1bb5c7da3aa1c4bf8a1d0df 버전 기존의 -i 옵션과 CLI 명령의 오타를
↑ 수정하였습니다.

#385 이슈 README.md 최종 수정

---

README.md
requirements.txt

readme에 발생한 오타 수정
입문자들을 배려하기 위하여 desiner → designer로 수정하였습니다

README.md 수정

---

coursegraph/show_table.py

[84a5392](https://github.com/oss2024hnu/coursegraph-py/commit/84a53920b49b1e8ba2d5dd0b16769769fd2c3789) 이 버전의 show_table_py의 생성자 인자 누락에 대해서 None, False, False값에 필요한 인자를 올바르게 전달하도록 코드를 수정하였습니다.
생성자에서 너비와 높이를 설정할 때 기본값을 추가하여 None 값이 들어오지 않도록 기본 너비와 높이 설정에 추가하였습니다.

#372 show_table.py 수정

---

coursegraph/show_graph.py

subjects가 None일 경우, 빈 딕셔너리를 반환하도록 설정하였습니다.
//최신버전으로 fork해서 다시 PR했습니다!

show_graph.py의 adjust_coordinates함수 개선

---

README.md

README에 -v, verbose 옵션에 대한 설명 추가

---

coursegraph/show_graph.py

예전에 작성되었던 show_graph.py 에 여러가지 함수가 추가되거나 함수의 내용이 변경되었으므로 그에 맞게 주석을 수정하고 주석이 없는 함수에 대해 주석을 추가하였습니다.

show_graph.py 에서 추가되거나 변경된 함수에 대하여 pydoc 를 사용할 수 있게 주석을 수정하거나 추가하였습니다.

---

coursegraph/gui.py

openFunction() 메서드와 saveAsFunction() 메서드에서 initial_dir 변수를 사용하여 사용자의 홈 디렉토리를 기본으로 설정하였습니다. 이를 통해 사용자가 파일을 열거나 저장할 때 기본적으로 사용자 홈 디렉토리가 열리도록 구현되었습니다.

파일 다이얼로그의 초기 경로 설정

---

coursegraph/show_graph.py

#371 
except PermissionError:
print("파일 읽기 권한이 없습니다.", file=sys.stderr)
return None
except IOError:
print("파일 읽기 중 오류가 발생했습니다.", file=sys.stderr)
return None
except Exception as e:
print(f"알 수 없는 오류가 발생했습니다: {e}", file=sys.stderr)
return None
추가 했습니다

show_graph.py read_subjects에 에러 검사 추가

---

coursegraph/__main__.py

- def verbose_0 과 같이 선언되어 있던 것을 
- def verbose_info 함수안에 넣고 level 을 선언해서 가독성을 높이고 코드 또한 간편하게 바꾸었습니다.

verbose 함수로 만든 후 수정 + input.file 과 output.file 여부 확인 관련 코드 수정

---

coursegraph/show_dot.py

dot파일에도 과목 구분 별로 테두리색을 변경, 범례를 추가하였습니다.

---

coursegraph/gui.py
coursegraph/show_dot.py

table, graph, schema 요소를 선택하지 않으면 경고 메세지가 나오게 변경

---

coursegraph/gui.py
coursegraph/show_dot.py

YAML 파일을 선택하면 선택된 파일의 절대 경로를 가져와서 현재 스크립트 파일의 경로를 기준으로 상대 경로로 변환하여 출력하도록 변경하였습니다

gui에서 yaml파일을 찾을 때 하드 코딩 된 것을 변경하였습니다

---

coursegraph/show_dot.py

- IOError를 캐치하여 파일 입출력 관련 오류 처리
- Exception을 캐치하여 그 외 예상치 못한 오류 처리

show_dot.py의 output_file 파라미터 예외 처리 개선

---

coursegraph/__main__.py

Reverts oss2024hnu/coursegraph-py#452

Revert "'-s' 옵션 파싱 수정"

---

coursegraph/show_dot.py

#509 에서 전반적인 띄어쓰기와 각 함수들이 무슨 기능을 하는지 알아보기 쉽게 주석을 추가하여 설명했습니다.

show_dot.py 주석 추가 및 띄어쓰기 수정

---

coursegraph/show_graph.py

```
bbox_props = dict(boxstyle=f"round,pad=0.5", ec='black', lw=2, facecolor='white')
for x in range(1,5):
plt.text(x,-0.18, f"{x}학년", fontsize=18, ha='center', va='center', fontweight='bold', bbox=bbox_props)
for y in range(0,2):
plt.text(0.6,y+0.5, f"{y}학기", fontsize=18, ha='center', va='center', fontweight='bold', bbox=bbox_props)
```
학기노드를 추가하였습니다

#503이슈 해결 학기노드 복원

---

coursegraph/show_table.py

[b3c67a6](https://github.com/oss2024hnu/coursegraph-py/commit/b3c67a6168908e8257ca35da344dda526311087a) 버전의 show_table.py를 가지고 표를 생성했을 때 학년과 학기를 더 잘 보일 수 있도록 표에 색을 입혔습니다. 
기존의 무색이였던 표에서
같은 학년은 비슷한 계열의 색상을 사용하여 구분이 잘되게 수정해 보았습니다. 이는 이전의 표보다 가독성이 좋을 듯 합니다.

과목 표 색상 추가

---

coursegraph/show_graph.py

#527 이슈의 관한 PR 내용입니다. 이슈에서 언급했듯이 컴퓨터의 문제일 수 있어서 폰트는 수정하지 않았습니다.

학기 노드 위치 수정

---

coursegraph/show_dot.py

파일 저장 중 예외 처리:
PermissionError: 파일 쓰기 권한이 없을 때 발생하는 오류를 처리. 이 경우 오류 메시지를 sys.stderr에 출력하고 None을 반환하여 함수를 종료합니다. IOError: 파일 입출력 중 발생하는 일반적인 오류를 처리합니다.
Exception: 기타 모든 예외를 포괄적으로 처리하며, 예기치 않은 오류 메시지를 sys.stderr에 출력하고 None을 반환합니다. 파일 저장 외의 예외 처리:
try 블록 전체에서 예외를 처리하여 그래프 생성 중에 발생할 수 있는 모든 예외를 포괄적으로 처리합니다. sys.stderr 사용:
모든 오류 메시지를 sys.stderr에 출력하도록 변경했습니다. 이를 통해 오류 메시지가 표준 출력과 구분되어 더 명확하게 오류를 확인할 수 있습니다. 이 수정된 코드는 다양한 파일 입출력 오류 및 기타 예외를 보다 세부적으로 처리하여 코드의 안정성을 높였습니다.

#511 코드 수정

---

coursegraph/show_dot.py

#540 
이슈와 #530 에 대해 해결한 내용입니다.
사용할 때 차이점은 없습니다.

-f dot 오류의 해결

---

coursegraph/show_table.py

show_table.py 함수 수정 충돌 수정본

---

coursegraph/show_table.py

table 오류 수정
