coursegraph/fontutil.py

윈도우, MacOS, 리눅스 의 폰트를 시스템 폰트 중 맑음, 애플고딕, 나눔고딕을 찾아 사용하도록 만들었습니다.
특히 MacOS의 경우 폰트 형식이 ttf가 아닌 otf를 사용하는 경우가 있기 때문에 ttf 폰트를 우선적으로 찾아보고 없을 시 otf 폰트를 찾아 출력하도록 만들었습니다.

coursegraph의 fontutil 을 수정한 후 추가하였습니다.

---

coursegraph/show_table.py

show_table.py에서 plt.tight_layout()함수를 사용하여 내용에 맞춰 화면을 출력하게끔 수정하였습니다.

테이블 출력시 일정 부분이 잘리는 현상 수정

---

coursegraph/Maingui.ui
coursegraph/gui.py

메인 UI를 실행 할 수 있도록 gui.py 를 수정했습니다.
제가 추가한 ui는 테스트를 위해 몇가지 위젯을 추가해 확인해보았습니다.
아래 사진은 추가한 UI의 모습입니다.
상단 메뉴에 현재 제작된 기능인 table을 보는 기능과 graph를 만드는 기능을 한 화면이 아닌 각기 다른 화면에 배치해 gui를 구성할 계획입니다.

GUI 라이브러리를 PyQt5 에 맞도록 변경했습니다.

---

coursegraph/Maingui.ui
coursegraph/gui.py
coursegraph/show_graph.py

#15 #110 에서 말한 
15의 원래 계획에 있던 일부 작업을
110에서 제안한 학기 구분선을 그려넣었습니다.
간단한 코드였기에 추가 설명은 필요 없을 것 같습니다.

학기 구분선을 추가하였습니다.

---

coursegraph/schema_checker.py

기존 코드에서 def validate_yaml(file_path): 함수의 try 문에 if subject["학년"] not in [1, 2, 3, 4, 5, 6]:  raise ValueError("학년은 1부터 6까지의 정수여야 합니다.") 의 코드를 추가하여 학년이 1~6 학년이 아닌 경우 error가 발생하게 수정하였습니다. 
이렇게 되면 실수로 음수나 소수점 등을 입력을 하더라도 1,2,3,4,5,6 이 아니기에 에러가 발생합니다.

schema_checker.py 에서 학년이 1~6 에 없는 경우 에러 발생하게 수정

---

coursegraph/gui.py

#246
위의 이슈 내용을 고치기 위해
gui.py의 6번째 줄에
form_class = uic.loadUiType("gui2.ui")[0]에서 "gui2.ui"를 같은 디렉토리에 있는 "Maingui.ui"로 변경하였습니다.
그 결과 cmd 창에서 python gui.py 실행 시 gui화면이 뜨게 되었습니다.

gui2.ui 를 Maingui.ui로 변경

---

coursegraph/Maingui.ui
coursegraph/gui.py

gui.py에서 다른 이름으로 저장이 가능하도록 수정했습니다.
그리고 파일을 열지 않고 다른이름으로 저장을 하려고 하면 warning메시지가 뜨게 수정했습니다.
파일을 열지 않은 상태에서 저장을 할 경우
warning메시지가 출력됩니다.
그리고 pushbutton을 이미지 초기화 버튼으로 수정해서 버튼을 누르면 연 이미지를 없앨 수 있습니다.

다른 이름으로 저장 기능 추가

---

coursegraph/show_graph.py

#270 
그래프 출력 시 나타나는 폰트 오류 문구가 뜨지 않도록 수정하여 해결하였습니다.

그래프 출력 시 뜨는 폰트 오류 해결

---

coursegraph/__main__.py
coursegraph/show_graph.py

#336이슈를 해결하였습니다. CLI창에서 노드들의 좌표데이터를 딕셔너리로 한데 묶어서 출력하는 기능을 추가하였습니다. 
0: [(1, -1.5)]
1: [(1, -0.8999999999999999)]
2: [(1, -0.3)]
3: [(1, 0.3)]
4: [(1, 0.8999999999999999)]
5: [(1, 1.5)]
6: [(2, -3.0)]
7: [(2, -2.4)]
8: [(2, -1.7999999999999998)]
9: [(2, -1.2)]
10: [(2, -0.6)]
11: [(2, 0.0)]
12: [(2, 0.6)]
... 이하 생략
키값은 노드번호를 의미하고
[(x,y)]으로 좌표의 위치를 알수 있습니다.
그래프 작업을 진행하면서 nx의 화면 출력방식이 특이하다고 느꼈는데 이 기능을 추가함으로써 실제 좌표와 화면 출력을 비교하며 좀 더 수월한 작업이 가능합니다.

#336 이슈 해결 CLI상에서 현재 출력 노드 좌표 데이터 출력

---

coursegraph/show_graph.py

과목이 전선, 전기, 교필 인지에 따라 전선이면 파랑색, 전기면 빨강색, 교필이면 초록색으로 테두리색을 설정하여 뭐가 전선인지 전기인지 한눈에 보기 편하게 하였습니다. 그리고 저희 ce.yaml 파일에서는 전선이랑 전기만 구분이 되있어서 전선, 전기, 교필만 우선 설정했습니다.

전선, 전기, 교필 과목 구분에 따라 테두리색 설정 및 과목에 따른 테두리색에 관한 범례 생성

---

coursegraph/__main__.py

c626aa75ff088f71b4c11281969181057d8ebdd4
가장 최신 버전까지 두가지 이슈가 해결되지 않았습니다.
#325 이슈의 오타가 수정되지 않아 수정했습니다.
#195 기존의 i, input 옵션은 필수적임에도 옵션을 지정해줘야했습니다.
-> 옵션인자 제거를 통해 -i, --input 옵션을 사용하지 않아도 동작하도록 수정했습니다.
`parser.add_argument('input', type=str, help='Specify the input YAML data file path. (required)')`
다음부터는 
```
heoseungbin@Heo coursegraph-py % python3 coursegraph/__main__.py data/input.yaml   
```
이런식으로 작성하면 됩니다.
동작모습

CLI -i 인자의 일반 argument 변환 + 오타수정 작업

---

Makefile
coursegraph/__main__.py

#364 
1. verbose 옵션이 정해지지 않은 경우 -> verbose = 0 -> 일반 사용자를 위해 출력 X
```
heoseungbin@Heo coursegraph-py % python3 coursegraph data/input.yaml 
```
```
WARNING:root:Verbose level 0
```
2. verbose = 1 인경우 축약된 정보만을 출력
```
heoseungbin@Heo coursegraph-py % python3 coursegraph data/input.yaml -v 1
```
```
INFO:root:Verbose level 1 : Summary Information
width * height : 20 * 10
The input YAML file path has been specified: data/input.yaml
The output image file path has been specified: None
```
3. verbose = 2 인경우 개발자를 위한 노드 위치 정보 + 디버그 로그 정보 출력
```
heoseungbin@Heo coursegraph-py % python3 coursegraph data/input.yaml -v 2
```
```
DEBUG:root:Verbose level 2 : Detailed Developer Information
width * height : 20 * 10
The input YAML file path has been specified: data/input.yaml
The output image file path …
```

v, verbose 옵션의 추가 

---

coursegraph/show_graph.py

#368 이슈에서와 같이 학기와 중앙선에 대해 언급한 내용을 바탕으로 학기 노드와 중앙선을 추가하였습니다.
↑ [8b84173](https://github.com/oss2024hnu/coursegraph-py/commit/8b8417387ccc93b9da2d551461ca104cee6e9020)버전의 학년 노드만 있는 그래프에서

학기 노드와 중앙 실선 추가

---

Makefile
README.md

#374  의
```
ifeq ($(OS), Windows_NT)
PYTHON=$(shell where python || where python3)
else
PYTHON=$(shell which python || which python3)
endif
CLICMD=$(PYTHON) coursegraph
```
python, python3을 구분하는 코드를 기입하여 운영체제가 window인지 아닌지로 python이나 python3으로 나눠 사용할 수 있게 해줍니다. 따라서 make test 명령어를 실행할 때, PYTHON 변수가 자동으로 적절한 파이썬 명령어(python 또는 python3)로 설정됩니다.
그리고 #417  에서 graphviz 패키지를 설치하여 사용해보니 다시 정상 작동이 되는 것을 확인해보았습니다.
Makefile 최종 수정본 6d6363b4e851d0247a8bb3fd3b4b68a1e28adea9 이 파일을 머지하시면 될 것 같습니다.

Makefile 수정본

---

coursegraph/__main__.py
coursegraph/show_dot.py
coursegraph/show_graph.py

#430 show_graph에서는 subject파일을 잘 만들어서 show_dot에 보내었지만 정작 show_dot함수에서 dot파일을 출력할 때 인코딩 조건을 적지 않고 출력한다는 사실을 발견하고 수정하였습니다. 이로써 dot 파일안에서 한글(한글로 된 과목이름들)이 제대로 출력됩니다.
/* Generated by GvGen v.1.0 (https://www.github.com/stricaud/gvgen) */
digraph G {
rankdir=TB;ranksep=1.25;
subgraph cluster1 {
label="1-1";
node47 [shape="note",label="프로그래밍실습"];
node48 [shape="note",label="이산구조"];
node49 [shape="note",label="컴퓨터개론"];
node50 [shape="note",label="웹스크립트프로그래밍"];
node51 [shape="note",label="디지털공학"];
node52 [color="green",style="dashed",label=""];
}
subgraph cluster8 {
label="4-2";
node9 [shape="note",label="데이터마이닝"];
node10 [shape="note",label="빅데이터"];
node11 [shape="note",label="머신러닝의이해"];
node12 [shape="note",label="프로젝트관리"];
node13 [shape="note",label="양자컴퓨팅"];
node59 …

#430이슈 해결 dot파일 생성시 한글 깨짐현상 수리

---

coursegraph/schema_checker.py

사용자가 유효한 파일명을 입력할 때까지 반복적으로 요구하며, validate_yaml 함수를 사용하여 파일의 유효성을 검사합니다. 만약 입력된 파일명이 유효하지 않으면, ValueError가 발생하고 다시 입력을 요구합니다. 유효한 파일명이 입력되면 반복문이 종료됩니다.

유효한 파일 입력할 때까지 사용자 입력 반복

---

coursegraph/show_graph.py

에러메세지를 'print' 대신 'logging'모듈을 사용합니다. -> import logging
'logger.error'을 사용해 에러 메시지를 기록하고
과목 데이터 입력시 데이터가 None인 경우도 로그를 기록합니다.
에러 처리와 로깅을 결합해 디버깅이나 문제 추적을 보다 쉽게 할 수 있습니다.

에러 처리 및 로깅 개선

---

coursegraph/show_table.py

#407 
make_data 메서드 내에서 DataFrame의 각 원소를 처리할 때 map 함수 대신 applymap 함수를 사용하여 성능을 개선하고 코드의 가독성을 향상시킬 수 있습니다. applymap 함수는 DataFrame의 각 셀에 대해 주어진 함수를 적용하므로, 전체 DataFrame에 대한 변환을 보다 효율적으로 수행할 수 있습니다.
변경된 점
df.stack().map(...).unstack() 방식을 df.applymap(...)로 변경했습니다. applymap은 DataFrame의 모든 원소에 대해 주어진 함수를 적용합니다. 이 경우, 리스트 타입의 데이터가 문자열로 변환될 수 있도록 처리하고 있습니다.

show_table.py에 appltmap을 활용하여 더 효율적인 벡터화 된 연산 사용

---

coursegraph/show_table.py

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
canvas를 사용하기 위하여 모듈을 추가 했습니다.

show_table.py canvas에 대한 모듈 누락 추가

---

coursegraph/schema_checker.py

validate_string_or_sequence 함수를 확장하고 개선하기 위해 re 모듈과 sys 모듈은 별도로 사용하지 않았으며, Union과 List 타입을 사용하기 위해 from typing import Union, List 구문을 추가
-> 함수 시그니처 변경
: value 파라미터의 타입을 Union[str, List[str], int]으로 변경하여 정수형 데이터도 지원합니다.

유효성 검사 함수 확장

---

coursegraph/show_graph.py

print(f"파일이 저장되었습니다: {output_file}") 함수를 추가하여 output_file이 지정된 경우 변수 저장 후, 
저장이 완료되면 print(f"파일이 저장되었습니다: {output_file}")을 출력합니다.
사용자가 저장한 파일을 저장 시 바로 보여주는 기능을 추가했습니다.

show_graph.py에서 print함수를 사용해 변수가 저장되었을 시 출력해서 사용자에게 보여주는 기능 추가

---

coursegraph/show_table.py

width, height 기본 너비와 높이의 설정이 잘못된 값으로 되어있었습니다.
명령어> python coursegraph -o out.png data/ce.yaml

사진이 비정상적으로 확대되어 화면에 출력됨 #469

---

coursegraph/show_graph.py

ce21d3b 버전의 show_graph.py 파일을 가지고 중앙선을 기준으로 하여 상단은 1학기 과목, 하단은 2학기 과목을 가리키도록 수정했습니다. 실행 결과 
정상적으로 작동되는 것을 확인했습니다.

show_graph.py 학기별 과목 나눔

---

coursegraph/show_table.py

기존 함수에서는 get_system_font 함수에서 불필요하게 반복문을 사용하고 있습니다. 
그래서 get_system_font 함수에서 for 반복문을 제거하고, 시스템 폰트 목록이 비어 있지 않으면 첫 번째 폰트 파일을 직접 반환하도록 변경했습니다.

show_table.py에서 불필요한 반복문의 제거

---

coursegraph/gui.py

'openFunction' 과 'saveAsFunction' 에서 파일 이름이 길 경우 앞부분을 생략하고 뒷부분만 표시하는 기능을 추가했습니다. 
메시지 표시 시간을  통일해 상태바 및 상태 표시줄에 메시지를 5초 동안만 표시하도록 통일했습니다.

gui.py에서 파일 이름이 길 경우 잘라서 표기하는 기능 추가

---

coursegraph/__main__.py

기존에는 코드에서 args.size.split('x')를 사용하여  파싱하고 있습니다. 이때 구분자로 사용하는 것이 ,인데 조금 더 표준적으로 바꾸기 위해 x로 바꿨습니다. 오류는 없지만 바꾸면 좋을 것 같습니다.
따라서 코드에서 args.size.split('x')로 변경하여 x를 구분자로 사용하는 것은 사용자가 입력하는 방식을 일반적인 사용 패턴에 맞추기 위한 것입니다.

'-s' 옵션 파싱 수정

---

coursegraph/fontutil.py

font_path에 target_font_name이 포함되어 있는지 먼저 검사합니다. 관심 있는 폰트 이름을 포함하지 않는 폰트 파일에 대해서는 FontProperties 객체 생성을 건너뛰어 성능을 개선합니다.
이러한 변경을 통해 시스템에 설치된 폰트 파일의 수가 많더라도, 관심 있는 폰트 파일만 빠르게 처리하여 결과를 얻을 수 있으므로 코드의 전체적인 성능이 향상됩니다.

fontutil.py의 성능 개선 및 최적화

---

coursegraph/show_graph.py

https://github.com/oss2024hnu/coursegraph-py/commit/c626aa75ff088f71b4c11281969181057d8ebdd4 버전 기준으로 화살표머리가 보이지 않게되었는데 화살표 머리가 보이도록 수정하였습니다. 아래는 그 예시사진입니다.

#356 이슈해결 화살표 머리 보이게 수정

---

coursegraph/show_graph.py

#537 이슈의 내용을 수정했습니다.
전필에 대한 색상을 추가하고 오른쪽 하단에도 색상과 전필을 추가했습니다.

graph 전필 추가
